theme: jekyll-theme-minimal
title: Brazilian Student Society for Aerospace R&D
description: A community of aerospace students for the development of open-source projects
logo: /logo.jpeg
google_analytics: UA-164523170-1
