theme: jekyll-theme-minimal
title: Brazilian Student Society for Aerospace R&D
description: A community of aerospace students for the development of open-source projects
logo: /logo.jpeg
logo_title: The rufous-bellied thrush (Turdus rufiventris) or Sabiá-Laranjeira. Art made by @dlott.
google_analytics: UA-164523170-1
trello: https://trello.com/bssaero
